# Copyright (C) 2005-2009, Parrot Foundation.
# $Id$

=head1 Using Lua on Parrot

=head2 In brief

C<lua.pbc> is the Lua interpreter.

=head2 Building

Retrieve Parrot

  svn checkout https://svn.parrot.org/parrot/trunk parrot

Configure & build & install Parrot

  cd parrot
  perl Configure.pl
  make
  sudo make install-dev

Retrieve Lua

  perl tools/dev/fetch_languages.pl --lang=lua

  cd languages/lua
  git submodule init t/lua-TestMore
  git submodule update

Configure & build Lua

  parrot Configure.pir
  make

=head2 Running the Test Suite

  make test

With t/lua-TestMore/test_lua51 is used as Test Suite

  make spectest

=head2 Smoking to Smolder

  make smoke

Note : t/lua-TestMore/test_lua51 is used as Test Suite

=head2 Running your own code

  ../../parrot lua.pbc example.lua

or in interactive mode :

  ../../parrot lua.pbc

=head2 Installing

  make install

and now :

  parrot-lua example.lua

=head2 Bugs & Limitations

See F<languages/lua/doc/status.pod>

=head2 See Also

F<languages/lua/doc/status.pod>

=head2 Author

Francois Perrad.

=cut

# Local Variables:
#   fill-column:78
# End:
# vim: expandtab shiftwidth=4:
